### ISSUE TITLE
Write automated tests for auth reset password endpoint

### ISSUE THREAD

**Issue by pitchinnate** [pitchinnate/gin-n-juice#14]
The default auth endpoint for reset password has no automated tests. Write automated tests to make sure everything works correctly (validation, password update).

**Comment by RotimiFreq** [comment]
Hi @pitchinnate I would like to work on this issue and other issues on test , do I need to be assigned to it or I can start writing the test?

**Comment by pitchinnate** [comment]
I can assign it to you.

**Comment by pitchinnate** [comment]
@RotimiFreq sorry I didn't realize I already have automated tests for most of the auth routes.
