### ISSUE TITLE
Make server hostname configurable via environment variable

### ISSUE THREAD

**Issue by pitchinnate** [pitchinnate/gin-n-juice#4]
Add a check for environment variable named SERVER_HOSTNAME that allows you to specify the hostname the server will use.

Should default to `localhost`.

**Comment by RohitShelke10** [comment]
I'd like to do this task

**Comment by RohitShelke10** [comment]
Please accept pull request @pitchinnate

**Comment by pitchinnate** [comment]
Completed with https://github.com/pitchinnate/gin-n-juice/pull/5
